version: '3'
services:
  api:
    build: ./api
    image: josepm/cic-api
    environment:
      TRANSLATE_KEY: ${TRANSLATE_KEY}
      VISION_KEY: ${VISION_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - monitor
  monitor:
    build: ./monitor
    image: josepm/cic-monitor
    environment:
      COSMOS_KEY: ${COSMOS_KEY}
    ports:
      - "5001:5001"
  logger:
    build: ./logger
    image: josepm/cic-logger
    environment:
      COSMOS_KEY: ${COSMOS_KEY}
    depends_on:
      - api
      - monitor
