apiVersion: v1
kind: Service
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  type: ClusterIP
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    app: monitor
